In [3]:
import numpy as np

PRIMER EJERCICIO

In [4]:
A = np.array([[1,4],[-1,3],[1,-9]])
cero = np.zeros((3,2))
r = A - A
print(r)

[[0 0]
 [0 0]
 [0 0]]


SEGUNDO EJERCICIO 

In [9]:
A = np.array([[3,0],[-1,5]])
B = np.array([[4,-2,1],[0,2,3]])
print(A)
print("////////////////////////")
print(B)

[[ 3  0]
 [-1  5]]
////////////////////////
[[ 4 -2  1]
 [ 0  2  3]]


In [14]:
print("A + (3B)")
B3 = 3 * B
print("Solo se puede realizar la multiplicación de la matriz B * 3")
print(B3)

A + (3B)


ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [11]:
print("A*B")
r2= A@B
print(r2)

A*B
[[12 -6  3]
 [-4 12 14]]


In [12]:
print("A^3")
r3 = A**3
print(r3)

A^3
[[ 27   0]
 [ -1 125]]


In [13]:
print("B^2")
r4 = B**2
print(r4)

B^2
[[16  4  1]
 [ 0  4  9]]


In [16]:
print("(5A) + B")
A5 = A * 5
r5 = A5@B
print(r5)

(5A) + B
[[ 60 -30  15]
 [-20  60  70]]


EJERCICIO TRES

In [19]:
restaurantes=np.array([[30,15,4],[25,18,8]])
tiendas=np.array([[1.2,2.2,4.5],[1.3,2.1,4.6]])
print(tiendas.T)
costoPorTienda=restaurantes@tiendas.T
print(costoPorTienda)
print("\nTienda 1", (costoPorTienda[0,0]+costoPorTienda[1,0]))
print("\nTienda 2", (costoPorTienda[0,1]+costoPorTienda[1,1]))

print("\nEs mejor comprar en la tienda 1")


[[1.2 1.3]
 [2.2 2.1]
 [4.5 4.6]]
[[ 87.   88.9]
 [105.6 107.1]]

Tienda 1 192.6

Tienda 2 196.0

Es mejor comprar en la tienda 1


EJERCICIO 4

In [37]:
almacen= np.array([[200,150,100],[75,100,125]])
costoV = np.array([[1.50,1.00,2.00],[1.75,1.50,1.00]])
matriz=costoV.T
print(matriz)

costoFin = almacen@matriz

print("Costo si se transporta en Camión:", (costoFin[0,0]+costoFin[1,0]))
print("Costo si se transporta en Tren:", (costoFin[0,1]+costoFin[1,1])) 

print("\n La mejor opción es transportarlo en Tren")


[[1.5  1.75]
 [1.   1.5 ]
 [2.   1.  ]]
Costo si se transporta en Camión: 1112.5
Costo si se transporta en Tren: 1081.25

 La mejor opción es transportarlo en Tren


Ejercio 5

In [46]:
ps = np.linalg.pinv(matriz)

print("3x + 2y = 6 \n6x + 4y = −9\n")

print(ps)
A = np.array([[0.09230769 , 0.04615385], [0.06153846 , 0.03076923]])
B = np.array([6,9])

resul = np.linalg.solve(A,B)
print(resul)
print("-----Comprobacion-----")
print(A@resul)



print("\nx + y = 3\nx − 4y = 1\n")
A = np.array([[1,1],[1,-4]])
B = np.array([3,1])

resul=np.linalg.solve(A,B)
print(resul)
print("-----Comprobacion-----")
print(A@resul)


print("\n2x − y + 2z = 3\n2x + 3y − z = 0\nx + 2y + 2z = −12\n")

A = np.array([[2,-1,2],[2,3,-1],[1,2,2]])
B = np.array([3,0,-12])

resul=np.linalg.solve(A,B)
print(resul)
print("-----Comprobacion-----")
print(A@resul)

3x + 2y = 6 
6x + 4y = −9

[[-0.15151515 -0.34848485  0.78787879]
 [ 0.42424242  0.57575758 -0.60606061]]
[ 7.50000145e+08 -1.50000000e+09]
-----Comprobacion-----
[6.         9.00000001]

x + y = 3
x − 4y = 1

[2.6 0.4]
-----Comprobacion-----
[3. 1.]

2x − y + 2z = 3
2x + 3y − z = 0
x + 2y + 2z = −12

[ 3.65217391 -3.7826087  -4.04347826]
-----Comprobacion-----
[ 3.00000000e+00  1.77635684e-15 -1.20000000e+01]
